name: CI/CD - Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache dependências do npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes
        run: npm run test --if-present

      - name: Build do Next.js
        run: npm run build

  build-and-push:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determinar a tag da imagem
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/caossim
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build e Push da imagem Next.js
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export PROJECT_DIR="prod"
            export HOST_PORT="3000"
            
            export IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/caossim"
            export IMAGE_TAG="latest"

            mkdir -p ~/$PROJECT_DIR

            echo '${{ secrets.DOCKER_COMPOSE_CONTENT }}' > ~/$PROJECT_DIR/docker-compose.yml

            echo "DOCKER_IMAGE_NAME=${IMAGE_NAME}" > ~/$PROJECT_DIR/.env
            echo "IMAGE_TAG=${IMAGE_TAG}" >> ~/$PROJECT_DIR/.env
            echo "HOST_PORT=${HOST_PORT}" >> ~/$PROJECT_DIR/.env

            cd ~/$PROJECT_DIR

            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

            docker compose pull
            docker compose up -d --remove-orphans
